from configs.config_base import make_dataset_config

enronmail = make_dataset_config(
    name="enronmail",
    type="Connection Mails",
    intro="a large database of over 600,000 emails generated by employees of the Enron Corporation, useful for email analysis and natural language processing tasks.",
    data_file="./data/enronmail/mails.jsonl",
    llm_model="gpt-4.1-nano",
    batch_size=512,
)
