from configs.config_base import make_dataset_config

fever = make_dataset_config(
    name="fever",
    type="General Knowledge",
    intro="consists of 185,445 claims generated by altering sentences extracted from Wikipedia and subsequently verified without knowledge of the sentence they were derived from. ",
    data_file="./data/fever/corpus.jsonl",
    llm_model="gpt-4.1-mini",
    batch_size=256,
)
